#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v27
# autospec commit: cd8d006
#
Name     : xpumanager
Version  : 1.2.41
Release  : 4
URL      : https://github.com/intel/xpumanager/archive/V1.2.41/xpumanager-1.2.41.tar.gz
Source0  : https://github.com/intel/xpumanager/archive/V1.2.41/xpumanager-1.2.41.tar.gz
Summary  : Intel(r) Performance Counter Monitor
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 ISSL MIT
Requires: xpumanager-bin = %{version}-%{release}
Requires: xpumanager-lib = %{version}-%{release}
Requires: xpumanager-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : doxygen
BuildRequires : fmt-dev
BuildRequires : gcc-staticdev
BuildRequires : glibc-dev
BuildRequires : igsc-dev
BuildRequires : libxml2-dev
BuildRequires : metee-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(hwloc)
BuildRequires : pkgconfig(level-zero)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : protobuf-dev
BuildRequires : pypi(grpcio_tools)
BuildRequires : python3-dev
BuildRequires : spdlog-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Disable-unneeded-third-party-inclusions.patch

%description
Intel(r) Performance Counter Monitor (Intel(r) PCM) is an application programming interface (API) and a set of tools based on the API to monitor performance and energy metrics of Intel(r) Core(tm), Xeon(r), Atom(tm) and Xeon Phi(tm) processors. PCM works on Linux, Windows, Mac OS X, FreeBSD and DragonFlyBSD operating systems.

%package bin
Summary: bin components for the xpumanager package.
Group: Binaries
Requires: xpumanager-license = %{version}-%{release}

%description bin
bin components for the xpumanager package.


%package dev
Summary: dev components for the xpumanager package.
Group: Development
Requires: xpumanager-lib = %{version}-%{release}
Requires: xpumanager-bin = %{version}-%{release}
Provides: xpumanager-devel = %{version}-%{release}
Requires: xpumanager = %{version}-%{release}

%description dev
dev components for the xpumanager package.


%package lib
Summary: lib components for the xpumanager package.
Group: Libraries
Requires: xpumanager-license = %{version}-%{release}

%description lib
lib components for the xpumanager package.


%package license
Summary: license components for the xpumanager package.
Group: Default

%description license
license components for the xpumanager package.


%prep
%setup -q -n xpumanager-1.2.41
cd %{_builddir}/xpumanager-1.2.41
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1749078027
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DDAEMONLESS=ON  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1749078027
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xpumanager
cp %{_builddir}/'xpumanager-%{version}/core/resources/amcfw/Intel Simplified Software License August 2021_Final_08.20.21_v2.txt' %{buildroot}/usr/share/package-licenses/xpumanager/e89dc4e901fb004ec02702b17b91015e236fac60 || :
cp %{_builddir}/xpumanager-%{version}/LICENSE.md %{buildroot}/usr/share/package-licenses/xpumanager/ed8b37fda2f9050d34d647cce7c56ef5312b45b9 || :
cp %{_builddir}/xpumanager-%{version}/core/resources/kernels/LICENSE %{buildroot}/usr/share/package-licenses/xpumanager/723eea2469244a92b3e3461b79c3e848ce058cc6 || :
cp %{_builddir}/xpumanager-%{version}/core/resources/mediadata/LICENSE %{buildroot}/usr/share/package-licenses/xpumanager/60e25f4a5bdd75aaaa1091247a05055c9c0e1e53 || :
cp %{_builddir}/xpumanager-%{version}/third_party/CLI11/LICENSE %{buildroot}/usr/share/package-licenses/xpumanager/12d7255123f8b212420b0e9509d51691754eba91 || :
cp %{_builddir}/xpumanager-%{version}/third_party/hwloc/COPYING %{buildroot}/usr/share/package-licenses/xpumanager/23ae9dd3b06c170d1abfbdf517a2e4fea90b7cdd || :
cp %{_builddir}/xpumanager-%{version}/third_party/json/LICENSE.MIT %{buildroot}/usr/share/package-licenses/xpumanager/4140ec0dd7a3673e6a3b3d2b3b0e91e56ad539f4 || :
cp %{_builddir}/xpumanager-%{version}/third_party/pcm/LICENSE %{buildroot}/usr/share/package-licenses/xpumanager/bc1bce20f86ca6c6fd42826da1fe7c5143d51f8c || :
cp %{_builddir}/xpumanager-%{version}/third_party/pcm/doc/license.txt %{buildroot}/usr/share/package-licenses/xpumanager/6f7b47278c4b6be718c293a5f372b69ac9e423a0 || :
cp %{_builddir}/xpumanager-%{version}/third_party/pcm/src/freegetopt/LICENSE %{buildroot}/usr/share/package-licenses/xpumanager/9f8d851ab4723bc3335332d5fa437327864b76c9 || :
cp %{_builddir}/xpumanager-%{version}/third_party/pcm/src/winpmem/LICENSE.txt %{buildroot}/usr/share/package-licenses/xpumanager/c8cf080da5f6389a9439dc1d4bbf792664e9f989 || :
cp %{_builddir}/xpumanager-%{version}/third_party/pcm/src/winring0/COPYRIGHT.txt %{buildroot}/usr/share/package-licenses/xpumanager/40d241bae1389e4dd21935b604a2f1b582bac103 || :
cp %{_builddir}/xpumanager-%{version}/third_party/spdlog/LICENSE %{buildroot}/usr/share/package-licenses/xpumanager/617ee17d495e6cb87f0d74cc2bddffaf5b827b1f || :
cp %{_builddir}/xpumanager-%{version}/third_party/spdlog/tests/catch.license %{buildroot}/usr/share/package-licenses/xpumanager/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/xpumanager-%{version}/windows/winxpum/core/lib-headers/spdlog/fmt/bundled/fmt.license.rst %{buildroot}/usr/share/package-licenses/xpumanager/a6571b819c2fb290e2bb182e92a7a20d7d42318d || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd
## install_append content
# Remove extraneous copies of license files that we already put in -licenses
rm -f %{buildroot}/usr/lib/xpu-smi/resources/*/*License*.txt
rm -f %{buildroot}/usr/lib/xpu-smi/resources/*/LICENSE
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/xpu-smi/config/diagnostics.conf
/usr/lib/xpu-smi/config/pci.conf
/usr/lib/xpu-smi/config/pci.ids
/usr/lib/xpu-smi/config/perf_metrics.conf
/usr/lib/xpu-smi/config/vgpu.conf
/usr/lib/xpu-smi/config/xpum.conf
/usr/lib/xpu-smi/config/xpum.conf.template
/usr/lib/xpu-smi/resources/kernels/test_multiple_memory_allocations.cl
/usr/lib/xpu-smi/resources/kernels/test_multiple_memory_allocations.spv
/usr/lib/xpu-smi/resources/kernels/ze_dp_compute.cl
/usr/lib/xpu-smi/resources/kernels/ze_dp_compute.spv
/usr/lib/xpu-smi/resources/kernels/ze_global_bw.cl
/usr/lib/xpu-smi/resources/kernels/ze_global_bw.spv
/usr/lib/xpu-smi/resources/kernels/ze_int_compute.cl
/usr/lib/xpu-smi/resources/kernels/ze_int_compute.spv
/usr/lib/xpu-smi/resources/kernels/ze_sp_compute.cl
/usr/lib/xpu-smi/resources/kernels/ze_sp_compute.spv
/usr/lib/xpu-smi/resources/mediadata/test_stream.264
/usr/lib/xpu-smi/resources/mediadata/test_stream_1080p.265
/usr/lib/xpu-smi/resources/mediadata/test_stream_4K.265

%files bin
%defattr(-,root,root,-)
/usr/bin/xpu-smi

%files dev
%defattr(-,root,root,-)
/usr/include/xpum_api.h
/usr/include/xpum_structs.h
/usr/lib64/libxpum.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxpum.so.1
/usr/lib64/libxpum.so.1.2.41

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xpumanager/12d7255123f8b212420b0e9509d51691754eba91
/usr/share/package-licenses/xpumanager/23ae9dd3b06c170d1abfbdf517a2e4fea90b7cdd
/usr/share/package-licenses/xpumanager/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/xpumanager/40d241bae1389e4dd21935b604a2f1b582bac103
/usr/share/package-licenses/xpumanager/4140ec0dd7a3673e6a3b3d2b3b0e91e56ad539f4
/usr/share/package-licenses/xpumanager/60e25f4a5bdd75aaaa1091247a05055c9c0e1e53
/usr/share/package-licenses/xpumanager/617ee17d495e6cb87f0d74cc2bddffaf5b827b1f
/usr/share/package-licenses/xpumanager/6f7b47278c4b6be718c293a5f372b69ac9e423a0
/usr/share/package-licenses/xpumanager/723eea2469244a92b3e3461b79c3e848ce058cc6
/usr/share/package-licenses/xpumanager/9f8d851ab4723bc3335332d5fa437327864b76c9
/usr/share/package-licenses/xpumanager/a6571b819c2fb290e2bb182e92a7a20d7d42318d
/usr/share/package-licenses/xpumanager/bc1bce20f86ca6c6fd42826da1fe7c5143d51f8c
/usr/share/package-licenses/xpumanager/c8cf080da5f6389a9439dc1d4bbf792664e9f989
/usr/share/package-licenses/xpumanager/e89dc4e901fb004ec02702b17b91015e236fac60
/usr/share/package-licenses/xpumanager/ed8b37fda2f9050d34d647cce7c56ef5312b45b9
